
# Dockerfile.python
FROM python:3.11-slim

WORKDIR /app

# Установим зависимости (если есть requirements.txt)
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt || true

# Копируем приложение
COPY . .

ENV PYTHONUNBUFFERED=1
EXPOSE 5000

CMD ["python", "main.py"]
